import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    in-out property <[string]> issue_titles: [];
    callback request-increase-value();
    callback request-first-issue-title();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }

        VerticalLayout {
            for issue_title in issue_titles: VerticalLayout {
                Text {
                    text: issue_title;
                }
            }
            Button {
                text: "Get first issue title";
                clicked => {
                    root.request-first-issue-title();
                }
            }
        }
    }
}
