import { Button, VerticalBox } from "std-widgets.slint";

export struct Issue {
    title: string,
}

export component AppWindow inherits Window {
    in-out property <int> counter: 42;
    in-out property <[Issue]> issues: [];
    callback request-increase-value();
    callback request-first-issue-title();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }

        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }

        VerticalLayout {
            for issue in issues: VerticalLayout {
                Text {
                    text: issue.title;
                }
            }
            Button {
                text: "Get first issue title";
                clicked => {
                    root.request-first-issue-title();
                }
            }
        }
    }
}
